version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: lion_app
    container_name: lion_app
    depends_on:
      - mongodb
    volumes:
      - .:/app:z
    env_file:
      - ./.mongo
    ports:
      - '8888:80'

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    env_file:
      - ./.mongo
