name: lesson1

on:
    push:
    pull_request:

jobs:
    echo-event:
        name: echo event
        runs-on: ubuntu-latest
        steps:
            - name: echo
              run: echo ${{github.event_name}}
              